# DaemonSetマニフェスト
apiVersion: apps/v1
kind: DaemonSet # DaemonSetで各ノード上でPodを稼働
metadata:
  name: ubuntu-daemonset
spec:
  selector:
    matchLabels:
      app: ubuntu
  template:
    metadata:
      labels:
        app: ubuntu
    spec:
      containers:
        - name: ubuntu
          image: ubuntu:22.04
          command: ["sh"]
          args:
            - -euc
            - "sleep infinity"
